name = "unera6"
compatibility_date = "2026-01-14"
pages_build_output_dir = "dist"

[vars]
JWT_SECRET = "unera_super_secret_2026_change_this_to_long_random_string"
FIREBASE_PROJECT_ID = "unera-50aae"

[[d1_databases]]
binding = "DB"
database_name = "unera3"
database_id = "9fc679a8-c734-4322-a205-ae91a5a318dd"

[[r2_buckets]]
binding = "R2"
bucket_name = "unera3"
